### ISSUE TITLE
Connect with companion app

### ISSUE THREAD

**Issue by AlleSchonWeg** [geocom/Wahoo-Sender#2]
Hi,
it is possible to connect the elemnt with the companion app and with your app at the same time?
Problem is, that you can only use companion or sender app. So live tracking is not working.

**Comment by geocom** [comment]
Was going to say no as some early testing I did before releasing the app this would not work but just did some testing and it looks like the official wahoo app will latch onto an existing connection.

So if you start Wahoo sender and connect it to your wahoo first then launch the official wahoo app the offical one will just connect and both apps will be able to use the connection.

Will look at adding in a blacklist for notifications right now if you use android 10 you will get a notification that location services are in use. Would expect that live tracking would send a ton of notifications to your wahoo because of this.

**Comment by AlleSchonWeg** [comment]
I testet it and you're right. If you first connect connect with sender and then companion app it works.
Two things which i observed:
- if the sender app goes to background the status changes to disconnected, but it's still connnected. Then the app crashes if you touch the back arrow.
- It is possible to auto connect the bolt after the first use?

**Comment by geocom** [comment]
Interesting that yours showed as disconnected mine always showed as connected.

Thanks for the pull request fixing that crash. Have pulled it in and will add it to the next release.

Have also put the auto connect question into a new issue just so it's easier for other people to find will close this issue as the original question has been resolved.
