### ISSUE TITLE
Reverse Engineering Wahoo

### ISSUE THREAD

**Issue by tomitrescak** [geocom/Wahoo-Sender#7]
Hello. Thanks for the amazing project! I'm Tomas, and with our team we are trying to help a patient with brain injury to recover, using his favourite activity cycling. For that purpose we have decided to buld a small cycling app and use Wahoo Cadence sensor to detect his movement.

We are stuck at reading the data from the Wahoo sensor. We are capable of receieving the desired data from the capability of our choosing, but we are receieving raw 5 bytes and we have no idea what they mean and how can we extract cadence from them. Wahoo support is not responsive and we have no idea how to continue. Their API is outdated, closed sourse disaster that does not work on PC.

We are using code from: https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/bluetoothle/ to detect and read data fro the sensor. But after that ... no idea.

Would you be so kind and share with us your approach on how can we reverse engineer those 5 bytes into meaningful code?

```cs
private async void Characteristic_ValueChanged(GattCharacteristic sender, GattValueChangedEventArgs args)
{
            // BT_Code: An Indicate or Notify reported that the value has changed.
            byte[] data;
            CryptographicBuffer.CopyToByteArray(args.CharacteristicValue, out data);

             // what now?
}
```

**Comment by geocom** [comment]
The way I did it was to use Androids Bluetooth HCI snoop log developer option from that you can open the data in wireshark and see what is being sent and received.

My guess would be that the sensor is going to be sending gyro information rather than a cadence value in order to save battery life and the maths for this is done on the phone I could be wrong about that but it does seem like the more likely option.

Can you share the 5 bytes & does the value change?

**Comment by tomitrescak** [comment]
Thanks for Your help! In the end I contacted some game manufacturers who use their sensors and they helped out by sending BT specs ;)
